
DROP INDEX lifeswitch_chat.final_answer_lifeswitch_provenance_owner_thread_v1;
DROP POLICY final_answer_lifeswitch_provenance_writer_v1 ON lifeswitch_chat.final_answer_lifeswitch_provenance_receipt_v1;
DROP TABLE lifeswitch_chat.final_answer_lifeswitch_provenance_receipt_v1;
