REVOKE SELECT ON lifeswitch_chat.read_prior_answer_lifeswitch_provenance_v1 FROM lifeswitch_chat_reader_v1;
DROP VIEW lifeswitch_chat.read_prior_answer_lifeswitch_provenance_v1;
DROP INDEX lifeswitch_chat.final_answer_lifeswitch_provenance_owner_thread_v1;
DROP POLICY final_answer_lifeswitch_provenance_writer_v1 ON lifeswitch_chat.final_answer_lifeswitch_provenance_receipt_v1;
DROP TABLE lifeswitch_chat.final_answer_lifeswitch_provenance_receipt_v1;
