BEGIN;

INSERT INTO lifeswitch_training.conditioning_library
  (slug, name, category, modality, purpose, default_duration_min, default_frequency_per_week,
   default_intensity, interference_risk, joint_stress, equipment, progression_notes,
   contraindication_notes, sort_order, is_active)
VALUES
  (
    'air_bike_intervals',
    'Air Bike Intervals',
    'intervals',
    'air_bike',
    'High-intensity conditioning with low impact but high systemic fatigue.',
    15,
    1,
    'Hard work intervals with easy recovery periods.',
    'high',
    'low_to_moderate',
    'air bike',
    'Start with short intervals and few rounds; add rounds before increasing intensity.',
    'Can compromise leg recovery and general recovery if placed near hard lower-body training.',
    160,
    true
  ),
  (
    'treadmill_intervals',
    'Treadmill Intervals',
    'intervals',
    'treadmill',
    'Controlled interval conditioning using speed, incline, or both.',
    20,
    1,
    'Moderate to hard intervals with easy recovery.',
    'moderate_to_high',
    'moderate_to_high',
    'treadmill',
    'Progress one variable at a time: rounds, duration, incline, or speed.',
    'Higher risk for foot, Achilles, knee, hip, or low-back irritation than low-impact modalities.',
    170,
    true
  ),
  (
    'sprint_intervals',
    'Sprint Intervals',
    'intervals',
    'running',
    'High-output conditioning for speed, power, and anaerobic capacity.',
    15,
    1,
    'Very hard efforts with full recovery.',
    'high',
    'high',
    'track, field, hill, or open space',
    'Use low volume first; increase only if tissue tolerance and mechanics are good.',
    'High injury and soreness risk; avoid with poor running tolerance, recent lower-body injury, or inadequate warm-up.',
    180,
    true
  ),
  (
    'battle_rope_intervals',
    'Battle Rope Intervals',
    'intervals',
    'battle_rope',
    'Upper-body and trunk-dominant conditioning with limited lower-body impact.',
    12,
    1,
    'Hard rope intervals with adequate rest.',
    'moderate',
    'low_to_moderate',
    'battle ropes',
    'Increase rounds before increasing interval length.',
    'Watch shoulder, elbow, wrist, neck, and grip tolerance.',
    190,
    true
  ),
  (
    'jump_rope_intervals',
    'Jump Rope Intervals',
    'intervals',
    'jump_rope',
    'Rhythmic conditioning, coordination, footwork, and calf stiffness tolerance.',
    10,
    1,
    'Short moderate to hard bouts with easy recovery.',
    'moderate',
    'moderate_to_high',
    'jump rope',
    'Start with brief bouts and low total contacts.',
    'Watch feet, calves, Achilles, knees, and bodyweight-related impact tolerance.',
    200,
    true
  ),
  (
    'suitcase_carry_conditioning',
    'Suitcase Carry Conditioning',
    'loaded_conditioning',
    'loaded_carry',
    'Unilateral loaded carry for trunk control, grip, posture, and work capacity.',
    12,
    1,
    'Moderate carries with controlled posture and breathing.',
    'moderate',
    'low_to_moderate',
    'dumbbell or kettlebell',
    'Increase distance or rounds before increasing load.',
    'Watch grip, low back, obliques, shoulder depression, and gait symmetry.',
    210,
    true
  ),
  (
    'trap_bar_carry_conditioning',
    'Trap-Bar Carry Conditioning',
    'loaded_conditioning',
    'loaded_carry',
    'Heavy loaded carry for total-body bracing, grip, and work capacity.',
    10,
    1,
    'Moderate to heavy carries with full control.',
    'moderate_to_high',
    'moderate',
    'trap bar',
    'Progress distance first, then load.',
    'Can interfere with deadlift, trap, grip, and low-back recovery.',
    220,
    true
  ),
  (
    'front_rack_carry_conditioning',
    'Front Rack Carry Conditioning',
    'loaded_conditioning',
    'loaded_carry',
    'Anterior loaded carry for trunk, upper back, breathing control, and posture.',
    10,
    1,
    'Moderate carries with upright posture.',
    'moderate',
    'moderate',
    'kettlebells, dumbbells, or sandbag',
    'Progress total distance before load.',
    'Watch wrist, elbow, shoulder, upper-back, and breathing tolerance.',
    230,
    true
  ),
  (
    'sled_pull_conditioning',
    'Sled Pull Conditioning',
    'loaded_conditioning',
    'sled',
    'Concentric-biased conditioning using backward or forward sled pulling.',
    15,
    1,
    'Moderate to hard pulls with rest.',
    'moderate_to_high',
    'moderate',
    'sled and straps or harness',
    'Start with short pulls and conservative load.',
    'Can compete with leg training; watch knees, hips, calves, Achilles, and low back.',
    240,
    true
  ),
  (
    'sandbag_carry_conditioning',
    'Sandbag Carry Conditioning',
    'loaded_conditioning',
    'loaded_carry',
    'Odd-object carry for trunk, upper back, grip, and general work capacity.',
    10,
    1,
    'Moderate carries with controlled breathing.',
    'moderate_to_high',
    'moderate',
    'sandbag',
    'Increase rounds or distance before load.',
    'Watch low back, biceps, grip, gait, and bracing fatigue.',
    250,
    true
  ),
  (
    'kettlebell_swings_conditioning',
    'Kettlebell Swings Conditioning',
    'metabolic_resistance',
    'kettlebell',
    'Posterior-chain power endurance and metabolic conditioning.',
    10,
    1,
    'Moderate to hard sets with crisp technique.',
    'moderate_to_high',
    'moderate',
    'kettlebell',
    'Progress total reps gradually while preserving hip-hinge mechanics.',
    'Avoid with poor hinge mechanics or irritable low back, hamstrings, hips, or shoulders.',
    260,
    true
  ),
  (
    'dumbbell_complex',
    'Dumbbell Complex',
    'metabolic_resistance',
    'dumbbell',
    'Sequenced dumbbell movements for metabolic resistance conditioning.',
    12,
    1,
    'Moderate to hard circuit with controlled form.',
    'moderate_to_high',
    'moderate',
    'dumbbells',
    'Add rounds before load; keep exercise transitions simple.',
    'Can interfere with strength training if placed too close to high-volume lifting.',
    270,
    true
  ),
  (
    'barbell_complex',
    'Barbell Complex',
    'metabolic_resistance',
    'barbell',
    'Sequenced barbell movements for advanced metabolic conditioning.',
    10,
    1,
    'Moderate to hard circuit; technique must remain clean.',
    'high',
    'moderate_to_high',
    'barbell',
    'Use simple movement chains and conservative loads.',
    'Higher skill and fatigue cost; avoid when technique breaks down or recovery is poor.',
    280,
    true
  ),
  (
    'bodyweight_circuit',
    'Bodyweight Circuit',
    'metabolic_resistance',
    'bodyweight',
    'General conditioning using bodyweight exercises.',
    15,
    2,
    'Easy to hard depending on exercise selection and rest periods.',
    'low_to_moderate',
    'low_to_moderate',
    'none or minimal equipment',
    'Progress by adding rounds, reps, density, or harder variations.',
    'Exercise choice should match joint tolerance and training age.',
    290,
    true
  ),
  (
    'step_up_conditioning_circuit',
    'Step-Up Conditioning Circuit',
    'metabolic_resistance',
    'step_up',
    'Lower-body conditioning using repeated step-ups or mixed step-up circuits.',
    12,
    1,
    'Moderate repeat efforts.',
    'moderate',
    'moderate',
    'box, bench, or step',
    'Progress step height, load, or volume slowly.',
    'Watch knees, hips, calves, foot tolerance, and lower-body recovery.',
    300,
    true
  ),
  (
    'walking_lunge_conditioning',
    'Walking Lunge Conditioning',
    'metabolic_resistance',
    'lunge',
    'Lower-body conditioning using repeated lunges for local muscular endurance.',
    10,
    1,
    'Moderate to hard sets with controlled mechanics.',
    'moderate_to_high',
    'moderate_to_high',
    'bodyweight, dumbbells, or kettlebells',
    'Progress total reps before load.',
    'Can strongly interfere with leg training and cause soreness; watch knees, hips, and adductors.',
    310,
    true
  ),
  (
    'box_jumps',
    'Box Jumps',
    'plyometric_power',
    'jump',
    'Low-rep power work emphasizing explosive takeoff and controlled landing.',
    8,
    1,
    'Explosive reps with full recovery; not conditioning by fatigue.',
    'moderate_to_high',
    'high',
    'plyo box',
    'Progress landing quality and low volume before height.',
    'Avoid high fatigue, poor landing mechanics, painful knees, painful feet, or poor balance.',
    320,
    true
  ),
  (
    'broad_jumps',
    'Broad Jumps',
    'plyometric_power',
    'jump',
    'Horizontal power work emphasizing hip extension and landing control.',
    8,
    1,
    'Explosive reps with full recovery.',
    'moderate_to_high',
    'high',
    'open floor or turf',
    'Progress volume cautiously; prioritize landing mechanics.',
    'High impact; watch feet, ankles, knees, hips, and low back.',
    330,
    true
  ),
  (
    'skater_bounds',
    'Skater Bounds',
    'plyometric_power',
    'lateral_bound',
    'Lateral plyometric work for frontal-plane power, control, and athleticism.',
    8,
    1,
    'Explosive lateral bounds with controlled landing.',
    'moderate_to_high',
    'high',
    'open floor or turf',
    'Start with small bounds and stable landings.',
    'Avoid if knee, ankle, hip, or balance control is poor.',
    340,
    true
  ),
  (
    'medicine_ball_slams',
    'Medicine Ball Slams',
    'plyometric_power',
    'medicine_ball',
    'Power conditioning using repeated overhead or rotational slams.',
    10,
    1,
    'Explosive reps with controlled reset.',
    'moderate',
    'low_to_moderate',
    'medicine ball',
    'Progress rounds or reps before ball weight.',
    'Watch shoulders, elbows, wrists, spine position, and fatigue-related form breakdown.',
    350,
    true
  ),
  (
    'medicine_ball_throws',
    'Medicine Ball Throws',
    'plyometric_power',
    'medicine_ball',
    'Explosive throwing work for power, rotation, and athletic expression.',
    8,
    1,
    'Explosive reps with full recovery.',
    'moderate',
    'low_to_moderate',
    'medicine ball and wall or open space',
    'Progress intent and quality before volume.',
    'Requires safe setup; watch shoulder, back, and rotational tolerance.',
    360,
    true
  ),
  (
    'jump_squats',
    'Jump Squats',
    'plyometric_power',
    'jump',
    'Power-focused lower-body plyometric using vertical projection.',
    8,
    1,
    'Explosive reps with full recovery.',
    'moderate_to_high',
    'high',
    'bodyweight or light load',
    'Use low volume and clean landings.',
    'Avoid with painful knees, feet, hips, or poor landing mechanics.',
    370,
    true
  ),
  (
    'plyo_pushups',
    'Plyo Push-Ups',
    'plyometric_power',
    'upper_body_plyometric',
    'Upper-body power work using explosive push-up variations.',
    8,
    1,
    'Explosive reps with full recovery.',
    'moderate',
    'moderate',
    'floor or elevated surface',
    'Start elevated if needed; progress range and explosiveness gradually.',
    'Watch wrists, elbows, shoulders, and trunk control.',
    380,
    true
  ),
  (
    'agility_ladder',
    'Agility Ladder',
    'athletic_conditioning',
    'agility',
    'Coordination, footwork, rhythm, and low-level athletic conditioning.',
    10,
    1,
    'Low to moderate skill-focused drills.',
    'low_to_moderate',
    'moderate',
    'agility ladder',
    'Progress complexity after rhythm and control are stable.',
    'Watch foot, ankle, calf, and knee tolerance; avoid turning skill work into sloppy fatigue.',
    390,
    true
  ),
  (
    'shuttle_runs',
    'Shuttle Runs',
    'athletic_conditioning',
    'change_of_direction',
    'Change-of-direction conditioning for field, court, and general athletic work.',
    12,
    1,
    'Moderate to hard repeated shuttles with rest.',
    'high',
    'high',
    'cones or open space',
    'Progress distance, speed, and volume carefully.',
    'Higher injury risk; watch ankles, knees, hips, adductors, and deceleration mechanics.',
    400,
    true
  ),
  (
    'cone_drills',
    'Cone Drills',
    'athletic_conditioning',
    'agility',
    'Patterned movement drills for acceleration, deceleration, and direction change.',
    12,
    1,
    'Moderate skill-focused conditioning.',
    'moderate_to_high',
    'moderate_to_high',
    'cones or markers',
    'Increase complexity before intensity; preserve mechanics.',
    'Watch fatigue-related breakdown and lower-body joint tolerance.',
    410,
    true
  ),
  (
    'mobility_flow',
    'Mobility Flow',
    'recovery',
    'mobility',
    'Low-intensity movement practice for recovery, range of motion, and readiness.',
    15,
    3,
    'Very easy to easy.',
    'very_low',
    'very_low',
    'mat or open floor',
    'Increase consistency before duration.',
    'Should reduce stiffness, not create fatigue or joint irritation.',
    420,
    true
  ),
  (
    'easy_swim',
    'Easy Swim',
    'recovery',
    'swimming',
    'Low-impact aerobic and recovery-oriented conditioning.',
    20,
    1,
    'Easy sustainable pace.',
    'low',
    'very_low',
    'pool',
    'Increase duration gradually.',
    'Watch shoulder tolerance and avoid turning recovery swimming into hard conditioning.',
    430,
    true
  ),
  (
    'pool_walking',
    'Pool Walking',
    'recovery',
    'pool',
    'Very low-impact gait, recovery, and reconditioning work.',
    20,
    2,
    'Very easy to easy.',
    'very_low',
    'very_low',
    'pool',
    'Increase duration or frequency gradually.',
    'Useful when land-based impact is poorly tolerated; monitor fatigue and balance.',
    440,
    true
  )
ON CONFLICT (slug) DO UPDATE
SET name=excluded.name,
    category=excluded.category,
    modality=excluded.modality,
    purpose=excluded.purpose,
    default_duration_min=excluded.default_duration_min,
    default_frequency_per_week=excluded.default_frequency_per_week,
    default_intensity=excluded.default_intensity,
    interference_risk=excluded.interference_risk,
    joint_stress=excluded.joint_stress,
    equipment=excluded.equipment,
    progression_notes=excluded.progression_notes,
    contraindication_notes=excluded.contraindication_notes,
    sort_order=excluded.sort_order,
    is_active=excluded.is_active,
    updated_at=now();

-- Normalize original conditioning entries into the broader loaded-conditioning category.
UPDATE lifeswitch_training.conditioning_library
SET category='loaded_conditioning',
    updated_at=now()
WHERE slug IN ('sled_push_conditioning', 'farmer_carry_conditioning');

COMMIT;
