from __future__ import annotations

"""One versioned registry for conversation provenance and runtime identifiers.

Legacy values remain exact because immutable rows and traces contain them.
Canonical values are declared here but are not activated until the paired
backend/frontend writer cutover. No other module may define a RESSE value.
"""


LEGACY_ASSISTANT_TRANSCRIPT_SOURCE_V1 = "backend/resse:assistant:v1"
LEGACY_CONVERSATION_RESPONSE_RUNTIME_V0_2 = "resse_response_v0_2"
LEGACY_LIFESWITCH_RESPONSE_RUNTIME_V0_3 = "resse_response_v0_3"
LEGACY_LIFESWITCH_RESPONSE_RUNTIME_V0_4 = "resse_response_v0_4"
LEGACY_CONVERSATION_SHADOW_TRACE_V0_6 = "resse_response_shadow_trace_v0_6"
LEGACY_CONVERSATION_SAFETY_ASSESSOR_V0_2 = "resse_safety_assessor_v0_2"
LEGACY_CONVERSATION_TRANSCRIPT_TAG_V0_2 = "resse_v0_2"
LEGACY_DEFAULT_ASSISTANT_PROFILE_V0_2 = "RESSE"

CANONICAL_ASSISTANT_TRANSCRIPT_SOURCE_V2 = "backend/seebx:assistant:v2"
CANONICAL_CONVERSATION_RESPONSE_RUNTIME_V1 = "conversation_response_v1"
CANONICAL_LIFESWITCH_RESPONSE_RUNTIME_V1 = "lifeswitch_response_v1"
CANONICAL_CONVERSATION_SHADOW_TRACE_V1 = "conversation_response_shadow_trace_v1"
CANONICAL_CONVERSATION_SAFETY_ASSESSOR_V1 = "conversation_safety_assessor_v1"
CANONICAL_CONVERSATION_TRANSCRIPT_TAG_V1 = "conversation_response_v1"
CANONICAL_DEFAULT_RESPONSE_PROFILE_V1 = "default_response_policy"

LEGACY_IDENTIFIER_VALUES = frozenset(
    {
        LEGACY_ASSISTANT_TRANSCRIPT_SOURCE_V1,
        LEGACY_CONVERSATION_RESPONSE_RUNTIME_V0_2,
        LEGACY_LIFESWITCH_RESPONSE_RUNTIME_V0_3,
        LEGACY_LIFESWITCH_RESPONSE_RUNTIME_V0_4,
        LEGACY_CONVERSATION_SHADOW_TRACE_V0_6,
        LEGACY_CONVERSATION_SAFETY_ASSESSOR_V0_2,
        LEGACY_CONVERSATION_TRANSCRIPT_TAG_V0_2,
        LEGACY_DEFAULT_ASSISTANT_PROFILE_V0_2,
    }
)
CANONICAL_IDENTIFIER_VALUES = frozenset(
    {
        CANONICAL_ASSISTANT_TRANSCRIPT_SOURCE_V2,
        CANONICAL_CONVERSATION_RESPONSE_RUNTIME_V1,
        CANONICAL_LIFESWITCH_RESPONSE_RUNTIME_V1,
        CANONICAL_CONVERSATION_SHADOW_TRACE_V1,
        CANONICAL_CONVERSATION_SAFETY_ASSESSOR_V1,
        CANONICAL_CONVERSATION_TRANSCRIPT_TAG_V1,
        CANONICAL_DEFAULT_RESPONSE_PROFILE_V1,
    }
)

if LEGACY_IDENTIFIER_VALUES & CANONICAL_IDENTIFIER_VALUES:
    raise RuntimeError("legacy and canonical conversation identifiers overlap")


__all__ = [
    "CANONICAL_ASSISTANT_TRANSCRIPT_SOURCE_V2",
    "CANONICAL_CONVERSATION_RESPONSE_RUNTIME_V1",
    "CANONICAL_CONVERSATION_SAFETY_ASSESSOR_V1",
    "CANONICAL_CONVERSATION_SHADOW_TRACE_V1",
    "CANONICAL_CONVERSATION_TRANSCRIPT_TAG_V1",
    "CANONICAL_DEFAULT_RESPONSE_PROFILE_V1",
    "CANONICAL_IDENTIFIER_VALUES",
    "CANONICAL_LIFESWITCH_RESPONSE_RUNTIME_V1",
    "LEGACY_ASSISTANT_TRANSCRIPT_SOURCE_V1",
    "LEGACY_CONVERSATION_RESPONSE_RUNTIME_V0_2",
    "LEGACY_CONVERSATION_SAFETY_ASSESSOR_V0_2",
    "LEGACY_CONVERSATION_SHADOW_TRACE_V0_6",
    "LEGACY_CONVERSATION_TRANSCRIPT_TAG_V0_2",
    "LEGACY_DEFAULT_ASSISTANT_PROFILE_V0_2",
    "LEGACY_IDENTIFIER_VALUES",
    "LEGACY_LIFESWITCH_RESPONSE_RUNTIME_V0_3",
    "LEGACY_LIFESWITCH_RESPONSE_RUNTIME_V0_4",
]
